const bucketUrl = 'https://storage.googleapis.com/bitte-public'
const tokensUrl = `${bucketUrl}/intents/tokens`
const chainsUrl = `${bucketUrl}/intents/chains`

export const TOKEN_ICONS: Record<string, string> = {
  BTC: `${tokensUrl}/btc_token.svg`,
  ETH: `${tokensUrl}/eth_token.svg`,
  NEAR: `${chainsUrl}/near.svg`,
  WNEAR: `${chainsUrl}/near.svg`,
  USDC: `${tokensUrl}/usdc_token.svg`,
  USDT: `${tokensUrl}/usdt_token.svg`,
  XDAI: `${tokensUrl}/xdai_token.svg`,
  DAI: `${tokensUrl}/xdai_token.svg`,
  SOL: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
  REF: 'https://assets.coingecko.com/coins/images/18279/small/ref.png',
  FRAX: 'https://assets.coingecko.com/coins/images/13422/small/FRAX_icon.png',
  AURORA: '/aurora.svg',
  JAMBO: 'https://plum-necessary-chameleon-942.mypinata.cloud/ipfs/QmVBgYM7SoEwsg1pZgi8gW6ZNi8HoQ8NZPgo8pzSDSZrQw',
  ARB: 'https://s2.coinmarketcap.com/static/img/coins/128x128/11841.png',
  DOGE: 'https://assets.coingecko.com/coins/images/5/small/dogecoin.png',
  XRP: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png',
  KNC: 'https://assets.coingecko.com/coins/images/947/small/kyber-logo.png',
  GMX: 'https://assets.coingecko.com/coins/images/18323/small/arbit.png',
  AAVE: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png',
  UNI: 'https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png',
  LINK: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
  SHIB: 'https://assets.coingecko.com/coins/images/11939/small/shiba.png',
  PEPE: 'https://assets.coingecko.com/coins/images/29850/small/pepe-token.jpeg',
  TRX: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png',
  ZEC: 'https://assets.coingecko.com/coins/images/486/small/circle-zcash-color.png',
  SUI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20947.png',
  APT: 'https://s2.coinmarketcap.com/static/img/coins/64x64/21794.png',
  ADA: 'https://assets.coingecko.com/coins/images/975/standard/cardano.png?1696502090',
  BLACKDRAGON: '/black_dragon.webp',
  SHITZU: '/shitzu.webp',
  PURGE: '/purge.png',
  ABG: '/abg.jpeg',
  KAITO: '/kaito.png',
  XBTC: `${tokensUrl}/btc_token.svg`,
  TURBO: 'https://assets.coingecko.com/coins/images/30117/standard/TurboMark-QL_200.png?1708079597',
  TRUMP: 'https://assets.coingecko.com/coins/images/53746/standard/trump.png?1737171561',
  MELANIA: 'https://assets.coingecko.com/coins/images/53775/standard/melania-meme.png?1737329885',
  WIF: "https://assets.coingecko.com/coins/images/33566/standard/dogwifhat.jpg?1702499428",
  WBTC: `${tokensUrl}/btc_token.svg`,
  CBBTC: `${tokensUrl}/btc_token.svg`,
  BRETT: 'https://assets.coingecko.com/coins/images/35529/standard/1000050750.png?1709031995',
  SWEAT: 'https://assets.coingecko.com/coins/images/25057/standard/fhD9Xs16_400x400.jpg?1696524208',
  USD1: 'https://assets.coingecko.com/coins/images/54977/standard/USD1_1000x1000_transparent.png?1749297002',
  MOG: 'https://assets.coingecko.com/coins/images/31059/standard/MOG_LOGO_200x200.png?1696529893',
  USDF: 'https://assets.coingecko.com/coins/images/54558/standard/ff_200_X_200.png?1740741076',
  GNO: 'https://assets.coingecko.com/coins/images/662/standard/logo_square_simple_300px.png?1696501854',
  SAFE: 'https://assets.coingecko.com/coins/images/27032/standard/Artboard_1_copy_8circle-1.png?1696526084',
  COW: 'https://assets.coingecko.com/coins/images/24384/small/cow.png',
  WETH: 'https://assets.coingecko.com/coins/images/2518/standard/weth.png?1696501626',
  RHEA: 'https://s2.coinmarketcap.com/static/img/coins/64x64/37529.png',
  BNB: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
  POL: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png',
  OP: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png',
  AVAX: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png',
  TON: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11419.png',
  PUBLIC: 'https://ref-new-1.s3.amazonaws.com/token/a7bac0ba58cbef0d117c76d9869bc2e0.svg',
}

export const CHAIN_ICONS: Record<string, string> = {
  cardano: 'https://assets.coingecko.com/coins/images/975/standard/cardano.png?1696502090',
  eth: `${chainsUrl}/eth.svg`,
  ethereum: `${chainsUrl}/eth.svg`,
  base: `${chainsUrl}/base.svg`,
  arb: `${chainsUrl}/arbi.svg`,
  arbitrum: `${chainsUrl}/arbi.svg`,
  gnosis: `${chainsUrl}/gnosis.svg`,
  near: `${chainsUrl}/near.svg`,
  aptos: 'https://s2.coinmarketcap.com/static/img/coins/64x64/21794.png',
  polygon: `${chainsUrl}/polygon.svg`,
  matic: `${chainsUrl}/polygon.svg`,
  op: `${chainsUrl}/op.svg`,
  optimism: `${chainsUrl}/op.svg`,
  avax: `${chainsUrl}/avax.svg`,
  avalanche: `${chainsUrl}/avax.svg`,
  bnb: `${chainsUrl}/bnb.svg`,
  bsc: `${chainsUrl}/bnb.svg`,
  sol: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
  btc: `${tokensUrl}/btc_token.svg`,
  sui: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20947.png',
  tron: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png',
  zec: "https://assets.coingecko.com/coins/images/486/small/circle-zcash-color.png",
  doge: "https://assets.coingecko.com/coins/images/5/small/dogecoin.png",
  xrp: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png',
  bera: "https://assets.coingecko.com/coins/images/25235/standard/BERA.png?1738822008",
  kaito: "https://assets.coingecko.com/coins/images/13422/small/FRAX_icon.png",
  fms: "https://s2.coinmarketcap.com/static/img/coins/64x64/29540.png",
  usdf: "https://s2.coinmarketcap.com/static/img/coins/64x64/29755.png",
  usd1: "https://s2.coinmarketcap.com/static/img/coins/64x64/31017.png",
  pol: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png',
  ton: "https://s2.coinmarketcap.com/static/img/coins/64x64/11419.png",
}

export function getTokenIcon(symbol: string): string | null {
  return TOKEN_ICONS[symbol.toUpperCase()] || null
}

export function getChainIcon(chain: string): string | null {
  return CHAIN_ICONS[chain.toLowerCase()] || null
}

